In [1]:
import requests
from datetime import datetime, timedelta
import random
import pickle
import json
import os
from time import sleep
import pandas as pd

In [2]:
dict_character = {}

def get_all_characters():
    for _id in range(1, 827):
        endpoint = f"https://rickandmortyapi.com/api/character/{_id}"
        response = requests.get(endpoint)
        
        dict_character[endpoint] = response.json()["name"]
get_all_characters()
dict_character

def complete_data(dataframe):
    total_data = []
    if dataframe == "character":
        pages = 42
    elif dataframe == "episode":
        pages = 3
    elif dataframe == "location":
        pages = 7
    for page in range(pages):
        endpoint = f"https://rickandmortyapi.com/api/{dataframe}/?page={page+1}"
        response = requests.get(endpoint)
        data = response.json()["results"]
        total_data.extend(data)
    return total_data

In [3]:




def fetch_data():
    
    datos_char = complete_data("character")
    datos_loc = complete_data("location")
    datos_epi = complete_data("episode")
    data = (datos_char,datos_loc,datos_epi)

    return data

def fix_col_dict(data_frame: pd.DataFrame, nombre_col):
    
    datos =[]
    
    for fila in data_frame[nombre_col]:
        datos.append(fila["name"])
        
    data_frame[f"{nombre_col}_nueva"] = datos
    
    # Borramos la columna y la devolvemos
    return data_frame.drop(nombre_col, axis=1)


def fix_url(dataframe, nombre_columna):
    
    lista_de_celdas = []
    
    for fila in dataframe[nombre_columna]:
        lista_de_nombres = []
        
        for url in fila:
            lista_de_nombres.append(dict_character[url])
        
        lista_de_celdas.append(lista_de_nombres)
        
    dataframe[nombre_columna] = lista_de_celdas

def trasnform_data(total_data):
    
    data_characters, data_locations, data_episodes = total_data
    
    df_characters = pd.DataFrame(data_characters)
    
    df_characters = fix_col_dict(df_characters, "origin")
    df_characters = fix_col_dict(df_characters, "location")
    
    df_characters = df_characters.drop(["image","episode","url", "created"],axis = 1)
    
    df_locations = pd.DataFrame(data_locations)
    fix_url(df_locations, "residents")
    df_locations = df_locations.drop(["url", "created"],axis = 1)
    
    df_episodes = pd.DataFrame(data_episodes)
    fix_url(df_episodes, "characters")
    df_episodes = df_episodes.drop(["url", "created"],axis = 1)
    
    return df_characters, df_locations, df_episodes

In [5]:
#EJECUCION 
data = fetch_data()
df_characters, df_locations, df_episodes = trasnform_data(data)

In [6]:
df_characters

,id,name,status,species,type,gender,origin_nueva,location_nueva
0,1,Rick Sanchez,Alive,Human,,Male,Earth (C-137),Citadel of Ricks
1,2,Morty Smith,Alive,Human,,Male,unknown,Citadel of Ricks
2,3,Summer Smith,Alive,Human,,Female,Earth (Replacement Dimension),Earth (Replacement Dimension)
3,4,Beth Smith,Alive,Human,,Female,Earth (Replacement Dimension),Earth (Replacement Dimension)
4,5,Jerry Smith,Alive,Human,,Male,Earth (Replacement Dimension),Earth (Replacement Dimension)
...,...,...,...,...,...,...,...,...
821,822,Young Jerry,unknown,Human,,Male,Earth (Unknown dimension),Earth (Unknown dimension)
822,823,Young Beth,unknown,Human,,Female,Earth (Unknown dimension),Earth (Unknown dimension)
823,824,Young Beth,unknown,Human,,Female,Earth (Unknown dimension),Earth (Unknown dimension)
824,825,Young Jerry,unknown,Human,,Male,Earth (Unknown dimension),Earth (Unknown dimension)
825,826,Butter Robot,Alive,Robot,Passing Butter Robot,Genderless,Earth (Replacement Dimension),Earth (Replacement Dimension)

In [7]:
df_episodes

,id,name,air_date,episode,characters
0,1,Pilot,"December 2, 2013",S01E01,"[Rick Sanchez, Morty Smith, Bepisian, Beth Smi..."
1,2,Lawnmower Dog,"December 9, 2013",S01E02,"[Rick Sanchez, Morty Smith, Beth Smith, Bill, ..."
2,3,Anatomy Park,"December 16, 2013",S01E03,"[Rick Sanchez, Morty Smith, Alexander, Annie, ..."
3,4,M. Night Shaym-Aliens!,"January 13, 2014",S01E04,"[Rick Sanchez, Morty Smith, Beth Smith, Cynthi..."
4,5,Meeseeks and Destroy,"January 20, 2014",S01E05,"[Rick Sanchez, Morty Smith, Beth Smith, Big Bo..."
5,6,Rick Potion #9,"January 27, 2014",S01E06,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
6,7,Raising Gazorpazorp,"March 10, 2014",S01E07,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
7,8,Rixty Minutes,"March 17, 2014",S01E08,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
8,9,Something Ricked This Way Comes,"March 24, 2014",S01E09,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
9,10,Close Rick-counters of the Rick Kind,"April 7, 2014",S01E10,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
10,11,Ricksy Business,"April 14, 2014",S01E11,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
11,12,A Rickle in Time,"July 26, 2015",S02E01,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
12,13,Mortynight Run,"August 2, 2015",S02E02,"[Rick Sanchez, Morty Smith, Jerry Smith, Arcad..."
13,14,Auto Erotic Assimilation,"August 9, 2015",S02E03,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
14,15,Total Rickall,"August 16, 2015",S02E04,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
15,16,Get Schwifty,"August 23, 2015",S02E05,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
16,17,The Ricks Must Be Crazy,"August 30, 2015",S02E06,"[Rick Sanchez, Morty Smith, Summer Smith, Atti..."
17,18,Big Trouble in Little Sanchez,"September 13, 2015",S02E07,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
18,19,Interdimensional Cable 2: Tempting Fate,"September 20, 2015",S02E08,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
19,20,Look Who's Purging Now,"September 27, 2015",S02E09,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
20,21,The Wedding Squanchers,"October 4, 2015",S02E10,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
21,22,The Rickshank Rickdemption,"April 1, 2017",S03E01,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
22,23,Rickmancing the Stone,"July 30, 2017",S03E02,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
23,24,Pickle Rick,"August 6, 2017",S03E03,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
24,25,Vindicators 3: The Return of Worldender,"August 13, 2017",S03E04,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
25,26,The Whirly Dirly Conspiracy,"August 20, 2017",S03E05,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
26,27,Rest and Ricklaxation,"August 27, 2017",S03E06,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
27,28,The Ricklantis Mixup,"September 10, 2017",S03E07,"[Rick Sanchez, Morty Smith, Beth Smith, Adjudi..."
28,29,Morty's Mind Blowers,"September 17, 2017",S03E08,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
29,30,The ABC's of Beth,"September 24, 2017",S03E09,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
30,31,The Rickchurian Mortydate,"October 1, 2017",S03E10,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
31,32,"Edge of Tomorty: Rick, Die, Rickpeat","November 10, 2019",S04E01,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
32,33,The Old Man and the Seat,"November 17, 2019",S04E02,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
33,34,One Crew Over the Crewcoo's Morty,"November 24, 2019",S04E03,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
34,35,Claw and Hoarder: Special Ricktim's Morty,"December 8, 2019",S04E04,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
35,36,Rattlestar Ricklactica,"December 15, 2019",S04E05,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
36,37,Never Ricking Morty,"May 3, 2020",S04E06,"[Tickets Please Guy, Floaty Bloody Man, Floaty..."
37,38,Promortyus,"May 10, 2020",S04E07,"[Angry Glorzo, Bruce, Council of Glorzos Membe..."
38,39,The Vat of Acid Episode,"May 17, 2020",S04E08,"[Rick Sanchez, Morty Smith, Beth Smith, Summer..."
39,40,Childrick of Mort,"May 24, 2020",S04E09,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
40,41,Star Mort: Rickturn of the Jerri,"May 31, 2020",S04E10,"[Rick Sanchez, Morty Smith, Summer Smith, Beth..."
41,42,Mort Dinner Rick Andre,"June 20, 2021",S05E01,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."
42,43,Mortyplicity,"June 27, 2021",S05E02,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."
43,44,A Rickconvenient Mort,"July 4, 2021",S05E03,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."
44,45,Rickdependence Spray,"July 11, 2021",S05E04,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."
45,46,Amortycan Grickfitti,"July 18, 2021",S05E05,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."
46,47,Rick & Morty's Thanksploitation Spectacular,"July 25, 2021",S05E06,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."
47,48,Gotron Jerrysis Rickvangelion,"August 1, 2021",S05E07,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."
48,49,Rickternal Friendshine of the Spotless Mort,"August 8, 2021",S05E08,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."
49,50,Forgetting Sarick Mortshall,"September 5, 2021",S05E09,"[Rick Sanchez, Morty Smith, Jerry Smith, Two C..."
50,51,Rickmurai Jack,"September 5, 2021",S05E10,"[Rick Sanchez, Morty Smith, Jerry Smith, Beth ..."

In [8]:
df_locations

,id,name,type,dimension,residents
0,1,Earth (C-137),Planet,Dimension C-137,"[Beth Smith, Bill, Conroy, Cronenberg Rick, Cr..."
1,2,Abadango,Cluster,unknown,[Abadango Cluster Princess]
2,3,Citadel of Ricks,Space station,unknown,"[Adjudicator Rick, Alien Morty, Alien Rick, An..."
3,4,Worldender's lair,Planet,unknown,"[Alan Rails, Crocubot, Logic, Million Ants, Su..."
4,5,Anatomy Park,Microverse,Dimension C-137,"[Alexander, Annie, Tuberculosis, Gonorrhea, He..."
...,...,...,...,...,...
121,122,Avian Planet,Planet,Replacement Dimension,"[Alien Crow, Alien Crow]"
122,123,Normal Size Bug Dimension,Dimension,,"[Palicki, Sarge]"
123,124,Slartivart,Planet,Replacement Dimension,[Slartivartian]
124,125,Rick and Two Crows Planet,Planet,Replacement Dimension,"[Pussifer, Crow Scare, Two Crows]"
125,126,Rick's Memories,Memory,,"[Punk Rick, Bald Rick, Beth Sanchez, Diane San..."